apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jimwhere-backend-ingress
  namespace: jimwhere
spec:
  ingressClassName: nginx
  rules:
    - host: api.jimwhere.local
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: jimwhere-backend
                port:
                  number: 8081