apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jimwhere-ingress
  namespace: jimwhere
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: jimwhere.local
      http:
        paths:
          # 프론트 (Vue)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jimwhere-frontend
                port:
                  number: 80

          #  백엔드 API
          - path: /api/v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: jimwhere-backend
                port:
                  number: 8081
