apiVersion: v1
kind: Secret
metadata:
  name: jimwhere-secret
  namespace: jimwhere
type: Opaque
stringData:
  DB_USERNAME: jimWhere
  DB_PASSWORD: jimWhere

  JWT_SECRET: rA/4r9fDxHVDBouXITwYw4nxNgmgshmA72NnxVpassNqZ038QCTpWznTn1UbekAwApd6oOA3/wixuu+4i0g2ww==

  BUSINESS_KEY: b4397be1e850da85e6cf138cc99933879ddb15e1a5e3114f651a79ad9d4bb376

  COOLSMS_API_KEY: NCS7G0C9OKW1FP92
  COOLSMS_API_SECRET: R0BNADXZKR0DMUMYSMMLBXWH8TGLOX5K
  COOLSMS_FROM_NUMBER: "01082802984"

  TOSS_SECRET_KEY: test_sk_26DlbXAaV064DwAgz9Qz8qY50Q9R
  TOSS_CLIENT_KEY: test_ck_DLJOpm5QrlWRQ6KDv70eVPNdxbWn
